Repository tintinweb/vscode-interactive-graphviz, pull requests merged in 2022-01, with the labels that each got.

#41 UI Development
  .gitignore
  .vscodeignore
  Licenses/@hpcc-wasm.LICENSE.md
  Licenses/@vscode-codicons.LICENSE.md
  Licenses/@vscode-webview-ui-toolkit.LICENSE.md
  Licenses/jquery-color.LICENSE.md
  Licenses/jquery.LICENSE.md
  README.md
  content/highlighting.js
  content/index.html
  content/save.js
  content/search.js
  content/toolbar/jquery.toolbar.css
  package-lock.json
  package.json
  src/extension.js
  src/features/interactiveWebview.js
  updateDependencies.js
Labels: enhancement

#49 Web extension
  .vscodeignore
  README.md
  content/index.html
  content/save.js
  content/toolbar/jquery.toolbar.css
  package-lock.json
  package.json
  src/extension.ts
  src/features/interactiveWebview.ts
  src/prepareHTML.ts
  webpack.config.js
Labels: enhancement, feature-request

#56 Overlapping toolbar (fixes #55)
  content/index.html
Labels: bug

#51 Cluster search
  content/graphvizSvg/jquery.graphviz.svg.js
  content/index.html
  content/search.js
  test/corpi/50_clusters.dot
Labels: enhancement, feature-request

#61 Fixes #11 (SVG export bug with HTML chars) - rebased off master
  content/save.js
Labels: bug
